#!/bin/bash

DIRS=(
    ~/code/projects
    ~/code/rtu
)

EXTRA=(
    ~/dotfiles
)

if [[ $# -eq 1 ]]; then
    selected=$1
else
    all_dirs=()

    for base in "${DIRS[@]}"; do
        label=$(basename "$base")
        while IFS= read -r sub; do
            sub_name=$(basename "$sub")
            all_entries+=("$label/$sub_name"$'\t'"$sub")
        done < <(find "$base" -mindepth 1 -maxdepth 1 -type d)
    done

    for path in "${EXTRA[@]}"; do
        abs=$(realpath "$path")
        name=$(basename "$abs")
        all_entries+=("extra/$name"$'\t'"$abs")
    done

    selected=$(printf "%s\n" "${all_entries[@]}" |
        fzf --ansi --border --padding 1,1 \
            --with-nth=1 --delimiter="\t" |
        cut -f2)

fi

if [[ -z $selected ]]; then
    echo "No directory selected. Press Enter to close..."
    read
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

read -p "Press Enter to close..."
