#!/bin/bash

source "$HOME/.config/sketchybar/vars.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar height=30 \
    blur_radius=30 \
    position=top \
    sticky=off \
    padding_left=10 \
    padding_right=10 \
    color=$BAR_COLOR

sketchybar --default icon.font="SF Pro:Semibold:15.0" \
    icon.color=$WHITE \
    label.font="SF Pro:Semibold:15.0" \
    label.color=$WHITE \
    background.color=$ITEM_BG_COLOR \
    background.corner_radius=5 \
    background.height=24 \
    padding_left=5 \
    padding_right=5 \
    label.padding_left=4 \
    label.padding_right=10 \
    icon.padding_left=10 \
    icon.padding_right=4

# -- Left Side Items --
source $ITEM_DIR/space.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
# source $ITEM_DIR/media.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
